services:
  - type: web
    name: image-guess-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
